### ISSUE TITLE
Why do we treat the protein channel differently?

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/2021_09_01_VarChAMP#18]
⚠️  tedium ahead! I confused myself after writing it down so I suggest we just discuss this in person, but feel free to add notes.

----

I’d find it so helpful if we can clearly articulate two things 

**1. In the context of controls, why should we think of the protein channel differently from a Cell Painting channel, say, the ER channel for the sake of this discussion?**

It is seemingly obvious, but if you take a simplified/abstracted view that all channels are just measuring some aspect of a cell’s phenotype, it’s less obvious to me.

I get it for no-protein negative controls — there’s nothing to mark in the protein channel. I'll note that there's no equivalent for the ER channel, that is, there isn't a "no-ER" negative control, and that's because the ER is always present and will therefore always be marked. Perhaps the only equivalent would be if a hypothetical negative control somehow destroyed the ability of Con A to bind to ER (without affecting the ER itself). In this case, all perturbations that didn't destroy the ability of Con A to bind to ER – whether or not they affected ER itself – would have a phenotype.

But what about a protein control that had any localization other than the protein of interest? Here you say the protein of interest will always have a phenotype. Why? Again, it is seemingly obvious because if we know the negative control has localization X, then any protein that doesn't have localization X will have a phenotype. Is there an equivalent for the ER channel? I suppose the equivalent is again a hypothetical negative control that would somehow change – but not destroy – the ability of Con A's binding to ER (without affecting the ER itself). In this case, all perturbations that didn't similarly change the ability of Con A to bind to ER – whether or not they affected ER itself – would have a phenotype.

All this leads to the next question

**2. What is a good negative control, when we limit ourselves only to the phenotype observed in the protein channel?**

---

Context:

Shantanu Singh
That said, if we’ve settled on negative controls, we can still use the framework for reporting phenotypic activity. 

Anne Carpenter
(which would be for the non-protein channels - the protein channel would always have a phenotype if we are comparing to no-protein controls, or if we choose a protein control that had any localization other than the protein of interest)

**Comment by AnneCarpenter** [comment]
That clarifies for me - I don't think generic neg controls are useful for direct comparison to samples in this experiment other than to establish the impact of plate layout effects and other technical variation.

For both protein channel and non protein channels, we really only want to know if the variant and reference differ.

It's more OBVIOUS for the protein channel, but the facts remain the same for Non-protein channels: these channels' morphology might be impacted by the presence of the reference protein expression and therefore the reference protein is the proper comparator for the variant of interest, we cannot use generic neg controls as the reference. I think I might've been confused by this before, thinking the non-protein channels would not be affected by overexpression of the protein of interest.

**Comment by bethac07** [comment]
Unasked for nitpick - your statement

> But when you use it to compare perturbations across genes, it's unclear what s_protein is reporting, because the similarity is across two different spaces. At first, I thought s_protein is a reasonable way to compare localization of two different proteins, but then (in Variant Painting) you are doing so across two different perturbation states, not the same perturbation state, and that makes things confusing. 

only is true if we assume/know that expression of the tagged version of the gene _is itself perturbing_. That is more likely to be the case in an overexpression context than a knock-in context, but even in OE, based on TA-ORF and MorphMap we definitely know not all OEs (and maybe not even MOST OEs) are.

**Comment by shntnu** [comment]
> only is true if we assume/know that expression of the tagged version of the gene is itself perturbing. That is more likely to be the case in an overexpression context than a knock-in context, but even in OE, based on TA-ORF and MorphMap we definitely know not all OEs (and maybe not even MOST OEs) are.

This is useful to keep in mind – thanks @bethac07
